# Generated by Django 4.1 on 2022-09-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coursedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_no', models.IntegerField()),
                ('course_name', models.CharField(max_length=30)),
                ('timings', models.TimeField()),
                ('starting_date', models.DateField(max_length=20)),
                ('duration', models.CharField(max_length=30)),
                ('fees', models.IntegerField()),
                ('trainer_name', models.CharField(max_length=30)),
            ],
        ),
    ]
